/* Generated by itemis CREATE code generator. */


#include "../src/sc_types.h"

#include "Statechart.h"

/*! \file
Implementation of the state machine 'Statechart'
*/

#ifndef SC_UNUSED
#define SC_UNUSED(P) (void)(P)
#endif

/* prototypes of all internal functions */
static void enseq_frontend_app_MainView_default(Statechart* handle);
static void enseq_frontend_app_ControlCenterView_default(Statechart* handle);
static void enseq_frontend_app_DirectionView_default(Statechart* handle);
static void enseq_frontend_app_RunningView_default(Statechart* handle);
static void enseq_frontend_app_MapPanelView_default(Statechart* handle);
static void enseq_frontend_app_DiagnosticsView_default(Statechart* handle);
static void enseq_frontend_app_default(Statechart* handle);
static void exseq_frontend_app_MainView(Statechart* handle);
static void exseq_frontend_app_ControlCenterView(Statechart* handle);
static void exseq_frontend_app_DirectionView(Statechart* handle);
static void exseq_frontend_app_RunningView(Statechart* handle);
static void exseq_frontend_app_MapPanelView(Statechart* handle);
static void exseq_frontend_app_DiagnosticsView(Statechart* handle);
static void exseq_frontend_app(Statechart* handle);
static void react_frontend_app__entry_Default(Statechart* handle);

/*! The reactions of state MainView. */
static sc_integer frontend_app_MainView_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state ControlCenterView. */
static sc_integer frontend_app_ControlCenterView_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state DirectionView. */
static sc_integer frontend_app_DirectionView_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state RunningView. */
static sc_integer frontend_app_RunningView_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state MapPanelView. */
static sc_integer frontend_app_MapPanelView_react(Statechart* handle, const sc_integer transitioned_before);

/*! The reactions of state DiagnosticsView. */
static sc_integer frontend_app_DiagnosticsView_react(Statechart* handle, const sc_integer transitioned_before);


static void clear_in_events(Statechart* handle);

static void micro_step(Statechart* handle);

/*! Performs a 'run to completion' step. */
static void run_cycle(Statechart* handle);






static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity);
static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq);
static void statechart_event_init(statechart_event * ev, StatechartEventID name);
static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq);
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev);
static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name);
static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event);
static statechart_event statechart_get_next_event(Statechart* handle);
static sc_boolean statechart_dispatch_next_event(Statechart* handle);


void statechart_init(Statechart* handle)
{
	sc_integer i;
	
	for (i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; ++i)
	{
		handle->stateConfVector[i] = Statechart_last_state;
	}
	
				
	clear_in_events(handle);
	
	
	
	handle->isExecuting = bool_false;
	statechart_eventqueue_init(&handle->in_event_queue, handle->in_buffer, STATECHART_IN_EVENTQUEUE_BUFFERSIZE);
}

void statechart_enter(Statechart* handle)
{
	/* Activates the state machine. */
	{
	};
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default enter sequence for statechart Statechart */
	enseq_frontend_app_default(handle);
	handle->isExecuting = bool_false;
}

void statechart_exit(Statechart* handle)
{
	/* Deactivates the state machine. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	/* Default exit sequence for statechart Statechart */
	exseq_frontend_app(handle);
	handle->stateConfVector[0] = Statechart_last_state;
	handle->isExecuting = bool_false;
}

/*!
Can be used by the client code to trigger a run to completion step without raising an event.
*/
void statechart_trigger_without_event(Statechart* handle) {
	run_cycle(handle);
}


sc_boolean statechart_is_active(const Statechart* handle)
{
	sc_boolean result = bool_false;
	sc_integer i;
	
	for(i = 0; i < STATECHART_MAX_ORTHOGONAL_STATES; i++)
	{
		result = result || handle->stateConfVector[i] != Statechart_last_state;
	}
	
	return result;
}

/* 
 * Always returns 'false' since this state machine can never become final.
 */
sc_boolean statechart_is_final(const Statechart* handle)
{
	SC_UNUSED(handle);
	return bool_false;
}

sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state)
{
	sc_boolean result = bool_false;
	switch (state)
	{
		case Statechart_frontend_app_MainView :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_FRONTEND_APP_MAINVIEW] == Statechart_frontend_app_MainView
			);
				break;
		case Statechart_frontend_app_ControlCenterView :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_FRONTEND_APP_CONTROLCENTERVIEW] == Statechart_frontend_app_ControlCenterView
			);
				break;
		case Statechart_frontend_app_DirectionView :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_FRONTEND_APP_DIRECTIONVIEW] == Statechart_frontend_app_DirectionView
			);
				break;
		case Statechart_frontend_app_RunningView :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_FRONTEND_APP_RUNNINGVIEW] == Statechart_frontend_app_RunningView
			);
				break;
		case Statechart_frontend_app_MapPanelView :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_FRONTEND_APP_MAPPANELVIEW] == Statechart_frontend_app_MapPanelView
			);
				break;
		case Statechart_frontend_app_DiagnosticsView :
			result = (sc_boolean) (handle->stateConfVector[SCVI_STATECHART_FRONTEND_APP_DIAGNOSTICSVIEW] == Statechart_frontend_app_DiagnosticsView
			);
				break;
			default:
				result = bool_false;
				break;
		}
		return result;
}

static void clear_in_events(Statechart* handle)
{
	handle->iface.returnToMain_raised = bool_false;
	handle->iface.goToRunning_raised = bool_false;
	handle->iface.goToControlCenter_raised = bool_false;
	handle->iface.goToDirection_raised = bool_false;
	handle->iface.returnToControlCenter_raised = bool_false;
	handle->iface.goToMapPanel_raised = bool_false;
	handle->iface.goToDiagnostics_raised = bool_false;
}

static void micro_step(Statechart* handle)
{
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_frontend_app_MainView :
		{
			frontend_app_MainView_react(handle,-1);
			break;
		}
		case Statechart_frontend_app_ControlCenterView :
		{
			frontend_app_ControlCenterView_react(handle,-1);
			break;
		}
		case Statechart_frontend_app_DirectionView :
		{
			frontend_app_DirectionView_react(handle,-1);
			break;
		}
		case Statechart_frontend_app_RunningView :
		{
			frontend_app_RunningView_react(handle,-1);
			break;
		}
		case Statechart_frontend_app_MapPanelView :
		{
			frontend_app_MapPanelView_react(handle,-1);
			break;
		}
		case Statechart_frontend_app_DiagnosticsView :
		{
			frontend_app_DiagnosticsView_react(handle,-1);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

static void run_cycle(Statechart* handle)
{
	/* Performs a 'run to completion' step. */
	if (handle->isExecuting == bool_true)
	{ 
		return;
	} 
	handle->isExecuting = bool_true;
	statechart_dispatch_next_event(handle);
	do
	{ 
		micro_step(handle);
		clear_in_events(handle);
	} while (statechart_dispatch_next_event(handle) == bool_true);
	handle->isExecuting = bool_false;
}


void statechart_raise_returnToMain(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_returnToMain);
	run_cycle(handle);
}

void statechart_raise_goToRunning(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_goToRunning);
	run_cycle(handle);
}

void statechart_raise_goToControlCenter(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_goToControlCenter);
	run_cycle(handle);
}

void statechart_raise_goToDirection(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_goToDirection);
	run_cycle(handle);
}

void statechart_raise_returnToControlCenter(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_returnToControlCenter);
	run_cycle(handle);
}

void statechart_raise_goToMapPanel(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_goToMapPanel);
	run_cycle(handle);
}

void statechart_raise_goToDiagnostics(Statechart* handle)
{
	statechart_add_event_to_queue(&(handle->in_event_queue), Statechart_goToDiagnostics);
	run_cycle(handle);
}






/* implementations of all internal functions */

/* 'default' enter sequence for state MainView */
static void enseq_frontend_app_MainView_default(Statechart* handle)
{
	/* 'default' enter sequence for state MainView */
	handle->stateConfVector[0] = Statechart_frontend_app_MainView;
}

/* 'default' enter sequence for state ControlCenterView */
static void enseq_frontend_app_ControlCenterView_default(Statechart* handle)
{
	/* 'default' enter sequence for state ControlCenterView */
	handle->stateConfVector[0] = Statechart_frontend_app_ControlCenterView;
}

/* 'default' enter sequence for state DirectionView */
static void enseq_frontend_app_DirectionView_default(Statechart* handle)
{
	/* 'default' enter sequence for state DirectionView */
	handle->stateConfVector[0] = Statechart_frontend_app_DirectionView;
}

/* 'default' enter sequence for state RunningView */
static void enseq_frontend_app_RunningView_default(Statechart* handle)
{
	/* 'default' enter sequence for state RunningView */
	handle->stateConfVector[0] = Statechart_frontend_app_RunningView;
}

/* 'default' enter sequence for state MapPanelView */
static void enseq_frontend_app_MapPanelView_default(Statechart* handle)
{
	/* 'default' enter sequence for state MapPanelView */
	handle->stateConfVector[0] = Statechart_frontend_app_MapPanelView;
}

/* 'default' enter sequence for state DiagnosticsView */
static void enseq_frontend_app_DiagnosticsView_default(Statechart* handle)
{
	/* 'default' enter sequence for state DiagnosticsView */
	handle->stateConfVector[0] = Statechart_frontend_app_DiagnosticsView;
}

/* 'default' enter sequence for region frontend_app */
static void enseq_frontend_app_default(Statechart* handle)
{
	/* 'default' enter sequence for region frontend_app */
	react_frontend_app__entry_Default(handle);
}

/* Default exit sequence for state MainView */
static void exseq_frontend_app_MainView(Statechart* handle)
{
	/* Default exit sequence for state MainView */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state ControlCenterView */
static void exseq_frontend_app_ControlCenterView(Statechart* handle)
{
	/* Default exit sequence for state ControlCenterView */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state DirectionView */
static void exseq_frontend_app_DirectionView(Statechart* handle)
{
	/* Default exit sequence for state DirectionView */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state RunningView */
static void exseq_frontend_app_RunningView(Statechart* handle)
{
	/* Default exit sequence for state RunningView */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state MapPanelView */
static void exseq_frontend_app_MapPanelView(Statechart* handle)
{
	/* Default exit sequence for state MapPanelView */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for state DiagnosticsView */
static void exseq_frontend_app_DiagnosticsView(Statechart* handle)
{
	/* Default exit sequence for state DiagnosticsView */
	handle->stateConfVector[0] = Statechart_last_state;
}

/* Default exit sequence for region frontend_app */
static void exseq_frontend_app(Statechart* handle)
{
	/* Default exit sequence for region frontend_app */
	/* Handle exit of all possible states (of Statechart.frontend_app) at position 0... */
	switch(handle->stateConfVector[ 0 ])
	{
		case Statechart_frontend_app_MainView :
		{
			exseq_frontend_app_MainView(handle);
			break;
		}
		case Statechart_frontend_app_ControlCenterView :
		{
			exseq_frontend_app_ControlCenterView(handle);
			break;
		}
		case Statechart_frontend_app_DirectionView :
		{
			exseq_frontend_app_DirectionView(handle);
			break;
		}
		case Statechart_frontend_app_RunningView :
		{
			exseq_frontend_app_RunningView(handle);
			break;
		}
		case Statechart_frontend_app_MapPanelView :
		{
			exseq_frontend_app_MapPanelView(handle);
			break;
		}
		case Statechart_frontend_app_DiagnosticsView :
		{
			exseq_frontend_app_DiagnosticsView(handle);
			break;
		}
		default: 
			/* do nothing */
			break;
	}
}

/* Default react sequence for initial entry  */
static void react_frontend_app__entry_Default(Statechart* handle)
{
	/* Default react sequence for initial entry  */
	enseq_frontend_app_MainView_default(handle);
}


static sc_integer frontend_app_MainView_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state MainView. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.goToDirection_raised == bool_true)
		{ 
			exseq_frontend_app_MainView(handle);
			enseq_frontend_app_DirectionView_default(handle);
			transitioned_after = 0;
		}  else
		{
			if (handle->iface.goToControlCenter_raised == bool_true)
			{ 
				exseq_frontend_app_MainView(handle);
				enseq_frontend_app_ControlCenterView_default(handle);
				transitioned_after = 0;
			} 
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer frontend_app_ControlCenterView_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state ControlCenterView. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.returnToMain_raised == bool_true)
		{ 
			exseq_frontend_app_ControlCenterView(handle);
			enseq_frontend_app_MainView_default(handle);
			transitioned_after = 0;
		}  else
		{
			if (handle->iface.goToRunning_raised == bool_true)
			{ 
				exseq_frontend_app_ControlCenterView(handle);
				enseq_frontend_app_RunningView_default(handle);
				transitioned_after = 0;
			}  else
			{
				if (handle->iface.goToMapPanel_raised == bool_true)
				{ 
					exseq_frontend_app_ControlCenterView(handle);
					enseq_frontend_app_MapPanelView_default(handle);
					transitioned_after = 0;
				}  else
				{
					if (handle->iface.goToDiagnostics_raised == bool_true)
					{ 
						exseq_frontend_app_ControlCenterView(handle);
						enseq_frontend_app_DiagnosticsView_default(handle);
						transitioned_after = 0;
					} 
				}
			}
		}
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer frontend_app_DirectionView_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state DirectionView. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.returnToMain_raised == bool_true)
		{ 
			exseq_frontend_app_DirectionView(handle);
			enseq_frontend_app_MainView_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer frontend_app_RunningView_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state RunningView. */
 			sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.returnToControlCenter_raised == bool_true)
		{ 
			exseq_frontend_app_RunningView(handle);
			enseq_frontend_app_ControlCenterView_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer frontend_app_MapPanelView_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state MapPanelView. */
	sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.returnToControlCenter_raised == bool_true)
		{ 
			exseq_frontend_app_MapPanelView(handle);
			enseq_frontend_app_ControlCenterView_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}

static sc_integer frontend_app_DiagnosticsView_react(Statechart* handle, const sc_integer transitioned_before)
{
	/* The reactions of state DiagnosticsView. */
	sc_integer transitioned_after = transitioned_before;
	if ((transitioned_after) < (0))
	{ 
		if (handle->iface.returnToControlCenter_raised == bool_true)
		{ 
			exseq_frontend_app_DiagnosticsView(handle);
			enseq_frontend_app_ControlCenterView_default(handle);
			transitioned_after = 0;
		} 
	} 
	/* If no transition was taken */
	if ((transitioned_after) == (transitioned_before))
	{ 
		/* then execute local reactions. */
		transitioned_after = transitioned_before;
	} 
	return transitioned_after;
}




static void statechart_eventqueue_init(statechart_eventqueue * eq, statechart_event *buffer, sc_integer capacity)
{
	eq->events = buffer;
	eq->capacity = capacity;
	eq->push_index = 0;
	eq->pop_index = 0;
	eq->size = 0;
}

static sc_integer statechart_eventqueue_size(statechart_eventqueue * eq)
{
	return eq->size;
}

static statechart_event statechart_eventqueue_pop(statechart_eventqueue * eq)
{
	statechart_event event;
	if(statechart_eventqueue_size(eq) <= 0) {
		statechart_event_init(&event, Statechart_invalid_event);
	}
	else {
		event = eq->events[eq->pop_index];
		
		if(eq->pop_index < eq->capacity - 1) {
			eq->pop_index++;
		} 
		else {
			eq->pop_index = 0;
		}
		eq->size--;
	}
	return event;
}
static sc_boolean statechart_eventqueue_push(statechart_eventqueue * eq, statechart_event ev)
{
	if(statechart_eventqueue_size(eq) == eq->capacity) {
		return bool_false;
	}
	else {
		eq->events[eq->push_index] = ev;
		
		if(eq->push_index < eq->capacity - 1) {
			eq->push_index++;
		}
		else {
			eq->push_index = 0;
		}
		eq->size++;
		
		return bool_true;
	}
}
static void statechart_event_init(statechart_event * ev, StatechartEventID name)
{
	ev->name = name;
}

static void statechart_add_event_to_queue(statechart_eventqueue * eq, StatechartEventID name)
{
	statechart_event event;
	statechart_event_init(&event, name);
	statechart_eventqueue_push(eq, event);
}

static sc_boolean statechart_dispatch_event(Statechart* handle, const statechart_event * event) {
	switch(event->name) {
		case Statechart_returnToMain:
		{
			handle->iface.returnToMain_raised = bool_true;
			return bool_true;
		}
		case Statechart_goToRunning:
		{
			handle->iface.goToRunning_raised = bool_true;
			return bool_true;
		}
		case Statechart_goToControlCenter:
		{
			handle->iface.goToControlCenter_raised = bool_true;
			return bool_true;
		}
		case Statechart_goToDirection:
		{
			handle->iface.goToDirection_raised = bool_true;
			return bool_true;
		}
		case Statechart_returnToControlCenter:
		{
			handle->iface.returnToControlCenter_raised = bool_true;
			return bool_true;
		}
		case Statechart_goToMapPanel:
		{
			handle->iface.goToMapPanel_raised = bool_true;
			return bool_true;
		}
		case Statechart_goToDiagnostics:
		{
			handle->iface.goToDiagnostics_raised = bool_true;
			return bool_true;
		}
		default:
			return bool_false;
	}
}

static statechart_event statechart_get_next_event(Statechart* handle)
{
	statechart_event next_event;
	statechart_event_init(&next_event, Statechart_invalid_event);
	if(statechart_eventqueue_size(&(handle->in_event_queue)) > 0) {
		next_event = statechart_eventqueue_pop(&(handle->in_event_queue));
	}
	return next_event;
}

static sc_boolean statechart_dispatch_next_event(Statechart* handle)
{
	statechart_event nextEvent;
	nextEvent = statechart_get_next_event(handle);
	return statechart_dispatch_event(handle, &nextEvent);
}
