/* Generated by itemis CREATE code generator. */

#ifndef STATECHART_H_
#define STATECHART_H_

#ifdef __cplusplus
extern "C" { 
#endif

/*!
* Forward declaration for the Statechart state machine.
*/
typedef struct Statechart Statechart;

/*!
* Forward declaration of the data structure for the StatechartIface interface scope.
*/
typedef struct StatechartIface StatechartIface;

#ifdef __cplusplus
}
#endif

#include "../src/sc_types.h"

#ifdef __cplusplus
extern "C" { 
#endif 

/*! \file
Header of the state machine 'Statechart'.
*/

#ifndef STATECHART_EVENTQUEUE_BUFFERSIZE
#define STATECHART_EVENTQUEUE_BUFFERSIZE 20
#endif
#ifndef STATECHART_IN_EVENTQUEUE_BUFFERSIZE
#define STATECHART_IN_EVENTQUEUE_BUFFERSIZE STATECHART_EVENTQUEUE_BUFFERSIZE
#endif
#ifndef SC_INVALID_EVENT_VALUE
#define SC_INVALID_EVENT_VALUE 0
#endif
/*! Define number of states in the state enum */
#define STATECHART_STATE_COUNT 8

/*! Define dimension of the state configuration vector for orthogonal states. */
#define STATECHART_MAX_ORTHOGONAL_STATES 1

/*! Define indices of states in the StateConfVector */
#define SCVI_STATECHART_FRONTEND_APP_MAINVIEW 0
#define SCVI_STATECHART_FRONTEND_APP_CONTROLCENTERVIEW 0
#define SCVI_STATECHART_FRONTEND_APP_DIRECTIONVIEW 0
#define SCVI_STATECHART_FRONTEND_APP_RUNNINGVIEW 0
#define SCVI_STATECHART_FRONTEND_APP_SETTINGSVIEW 0
#define SCVI_STATECHART_FRONTEND_APP_DIAGNOSTICSVIEW 0
#define SCVI_STATECHART_FRONTEND_APP_MAPPANELVIEW 0
#define SCVI_STATECHART_FRONTEND_APP_CHATVIEW 0


/* 
 * Enum of event names in the statechart.
 */
typedef enum  {
	Statechart_invalid_event = SC_INVALID_EVENT_VALUE,
	Statechart_returnToMain,
	Statechart_goToRunning,
	Statechart_goToControlCenter,
	Statechart_goToDirection,
	Statechart_returnToControlCenter,
	Statechart_goToSettings,
	Statechart_goToDiagnostics,
	Statechart_goToMapPanel,
	Statechart_goToChatView
} StatechartEventID;

/*
 * Struct that represents a single event.
 */
typedef struct {
	StatechartEventID name;
} statechart_event;

/*
 * Queue that holds the raised events.
 */
typedef struct statechart_eventqueue_s {
	statechart_event *events;
	sc_integer capacity;
	sc_integer pop_index;
	sc_integer push_index;
	sc_integer size;
} statechart_eventqueue;

/*! Enumeration of all states */ 
typedef enum
{
	Statechart_last_state,
	Statechart_frontend_app_MainView,
	Statechart_frontend_app_ControlCenterView,
	Statechart_frontend_app_DirectionView,
	Statechart_frontend_app_RunningView,
	Statechart_frontend_app_SettingsView,
	Statechart_frontend_app_DiagnosticsView,
	Statechart_frontend_app_MapPanelView,
	Statechart_frontend_app_ChatView
} StatechartStates;


/*! Type declaration of the data structure for the StatechartIface interface scope. */
struct StatechartIface
{
	sc_boolean returnToMain_raised;
	sc_boolean goToRunning_raised;
	sc_boolean goToControlCenter_raised;
	sc_boolean goToDirection_raised;
	sc_boolean returnToControlCenter_raised;
	sc_boolean goToSettings_raised;
	sc_boolean goToDiagnostics_raised;
	sc_boolean goToMapPanel_raised;
	sc_boolean goToChatView_raised;
};






/*! 
 * Type declaration of the data structure for the Statechart state machine.
 * This data structure has to be allocated by the client code. 
 */
struct Statechart
{
	StatechartStates stateConfVector[STATECHART_MAX_ORTHOGONAL_STATES];
	StatechartIface iface;
	sc_boolean isExecuting;
	statechart_eventqueue in_event_queue;
	statechart_event in_buffer[STATECHART_IN_EVENTQUEUE_BUFFERSIZE];
};



/*! Initializes the Statechart state machine data structures. Must be called before first usage.*/
extern void statechart_init(Statechart* handle);


/*! Activates the state machine. */
extern void statechart_enter(Statechart* handle);

/*! Deactivates the state machine. */
extern void statechart_exit(Statechart* handle);

/*! 
Can be used by the client code to trigger a run to completion step without raising an event.
*/
extern void statechart_trigger_without_event(Statechart* handle);



/*! Raises the in event 'returnToMain' that is defined in the default interface scope. */ 
extern void statechart_raise_returnToMain(Statechart* handle);
/*! Raises the in event 'goToRunning' that is defined in the default interface scope. */ 
extern void statechart_raise_goToRunning(Statechart* handle);
/*! Raises the in event 'goToControlCenter' that is defined in the default interface scope. */ 
extern void statechart_raise_goToControlCenter(Statechart* handle);
/*! Raises the in event 'goToDirection' that is defined in the default interface scope. */ 
extern void statechart_raise_goToDirection(Statechart* handle);
/*! Raises the in event 'returnToControlCenter' that is defined in the default interface scope. */ 
extern void statechart_raise_returnToControlCenter(Statechart* handle);
/*! Raises the in event 'goToSettings' that is defined in the default interface scope. */ 
extern void statechart_raise_goToSettings(Statechart* handle);
/*! Raises the in event 'goToDiagnostics' that is defined in the default interface scope. */ 
extern void statechart_raise_goToDiagnostics(Statechart* handle);
/*! Raises the in event 'goToMapPanel' that is defined in the default interface scope. */ 
extern void statechart_raise_goToMapPanel(Statechart* handle);
/*! Raises the in event 'goToChatView' that is defined in the default interface scope. */ 
extern void statechart_raise_goToChatView(Statechart* handle);

/*!
 * Checks whether the state machine is active (until 2.4.1 this method was used for states).
 * A state machine is active if it was entered. It is inactive if it has not been entered at all or if it has been exited.
 */
extern sc_boolean statechart_is_active(const Statechart* handle);

/*!
 * Checks if all active states are final. 
 * If there are no active states then the state machine is considered being inactive. In this case this method returns false.
 */
extern sc_boolean statechart_is_final(const Statechart* handle);

/*! Checks if the specified state is active (until 2.4.1 the used method for states was called isActive()). */
extern sc_boolean statechart_is_state_active(const Statechart* handle, StatechartStates state);


#ifdef __cplusplus
}
#endif 

#endif /* STATECHART_H_ */
